# Triggering the workflow


name: Deploy .NET App to Azure

on:
  push:
    branches:
      - main  # this means: run when I push code to the "main" branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # use a free Linux VM to run the job

    steps:
      - name: Checkout code from GitHub
        uses: actions/checkout@v3

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'  # or 6.0.x or whatever version your project uses

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --configuration Release --no-restore

      - name: Publish the project
        run: dotnet publish --configuration Release --output ./output

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: dotnetstudentwebapp  # <-- Replace with your actual Azure App name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./output
